#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_Request_Status:
    path: /api/v1/status/{applicationId}
    controller: App\Controller\Api\v1\RequestStatusController::newRequest
    schemes: [https]